[project]
name = "LaTeXTools"
version = "4.5.15"
description = "LaTeX plugin for Sublime Text"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[tool.black]
exclude = '''
/(
  | \.git
  | \.github
  | \.ruff_cache
  | \.venv
  | tests
  | vendor
)/
'''
line-length = 100
target-version = ['py38']

[tool.ruff]
exclude = [
  ".git",
  ".github",
  ".ruff_cache",
  ".venv",
  "tests",
  "vendor"
]
line-length = 100
target-version = "py38"

[tool.ruff.lint.per-file-ignores]
"plugin.py" = ["F401"]
