#!/bin/sh

# We need to remove the stupid "file://" that Evince puts in front of the file name
EDITORCMD='f="%f"; sublime-text ${f#file://}:%l'

PDFFILE="$1"
if [ -f "$PDFFILE" ];then
	# danke an Feuerfieber
	# http://forum.ubuntuusers.de/topic/evince-synctex-vim-emacs-scite-lyx-kile-editor/#post-2841828
	if [ -f "${PDFFILE%%.pdf}.synctex.gz" ];then
		# we change the cwd to this directory, ./evince_backward_search should work
		./evince_backward_search "$PDFFILE" "$EDITORCMD"&
		BACKWARD_SEARCH_PID=$!
		echo $BACKWARD_SEARCH_PID
	fi
fi

/usr/bin/evince "$@"

if [ "$BACKWARD_SEARCH_PID" ];then
	echo "Killing $BACKWARD_SEARCH_PID"
	kill $BACKWARD_SEARCH_PID
fi
